# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := fbx-conv
INSTALL_PATH?=/usr/local

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

check:
	@[ "${FBX_SDK_ROOT}" ] || ( echo "ERROR: FBX_SDK_ROOT is not set"; exit 1 )

fbx-conv: check 
	@${MAKE} --no-print-directory -C . -f fbx-conv.make

install: 
	cp fbx-conv ${INSTALL_PATH}/bin/

clean:
	@${MAKE} --no-print-directory -C . -f fbx-conv.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   fbx-conv"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
